#!/bin/bash

# la4j
wget http://central.maven.org/maven2/org/la4j/la4j/0.6.0/la4j-0.6.0.jar

# Jama
wget http://math.nist.gov/javanumerics/jama/Jama-1.0.3.jar

# ejml # efficient?
#wget http://downloads.sourceforge.net/project/ejml/v0.28/ejml-v0.28-libs.zip
#unzip ejml-v0.28-libs.zip
#mv ejml-v0.28-libs/* .
#rm ejml-v0.28-libs.zip
#rm -rf ejml-v0.28-libs
wget http://central.maven.org/maven2/com/googlecode/efficient-java-matrix-library/ejml/0.25/ejml-0.25.jar

# commons math
wget http://supergsego.com/apache//commons/math/binaries/commons-math3-3.5-bin.tar.gz
tar xzf commons-math3-3.5-bin.tar.gz commons-math3-3.5/commons-math3-3.5.jar
mv commons-math3-3.5/commons-math3-3.5.jar .
rm commons-math3-3.5-bin.tar.gz
rm -r commons-math3-3.5

# Parallel Colt
wget http://central.maven.org/maven2/net/sourceforge/parallelcolt/parallelcolt/0.10.0/parallelcolt-0.10.0.jar

# ojAlgo
wget http://central.maven.org/maven2/org/ojalgo/ojalgo/46.3.0/ojalgo-46.3.0.jar
